// Generated by CoffeeScript 1.9.3
(function() {
  var fs, main, nodemailer, syntax;

  fs = require('fs');

  nodemailer = require('nodemailer');

  syntax = function() {
    console.log("Syntax: xmas [-h]");
    console.log("        xmas inputList username password");
    return process.exit(1);
  };

  main = function() {
    var args, blacklist, body, dst, emailPassword, emailUsername, i, index, inputList, j, k, l, len, len1, len2, len3, len4, line, lines, m, mailOptions, name, people, person, pieces, presents, ref, results, transporter;
    args = require('minimist')(process.argv.slice(2), {
      boolean: ['h', 'v', 'c', 'u', 'x'],
      string: ['t', 'm', 's'],
      alias: {
        help: 'h'
      }
    });
    if (args.help || args._.length < 3) {
      syntax();
    }
    inputList = args._[0];
    emailUsername = args._[1];
    emailPassword = args._[2];
    console.log("inputList    : " + inputList);
    console.log("emailUsername: " + emailUsername);
    console.log("emailPassword: " + emailPassword);
    lines = String(fs.readFileSync(inputList)).split(/[\r\n]/);
    people = [];
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      pieces = line.split(/\s+/);
      if (pieces.length >= 2) {
        blacklist = {};
        ref = pieces.slice(2);
        for (j = 0, len1 = ref.length; j < len1; j++) {
          name = ref[j];
          blacklist[name] = true;
        }
        person = {
          name: pieces[0],
          email: pieces[1],
          blacklist: blacklist,
          dst: null,
          santa: false
        };
        people.push(person);
      }
    }
    console.log(people);
    console.log("If this sits here more than 5 seconds without printing the present list, break and try again. This is so lame.");
    presents = {};
    for (k = 0, len2 = people.length; k < len2; k++) {
      person = people[k];
      while (true) {
        index = Math.floor(Math.random() * people.length);
        dst = people[index];
        if ((dst.name !== person.name) && !dst.santa && !person.blacklist[dst.name]) {
          person.dst = dst;
          dst.santa = person;
          break;
        }
      }
    }
    for (l = 0, len3 = people.length; l < len3; l++) {
      person = people[l];
      console.log(person.santa.name + " buys a present for " + person.name);
    }
    transporter = nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: emailUsername,
        pass: emailPassword
      }
    });
    results = [];
    for (m = 0, len4 = people.length; m < len4; m++) {
      person = people[m];
      console.log(person.santa.name + " buys a present for " + person.name);
      body = "Hello, " + person.santa.name + "!<br>\n<br>\nPlease get a present for <b>" + person.name + "</b>. <i>Merry Christmas!</i><br>\n<br>\n-- The Christmas Thing<br>\n<br>\nPS. <b><i>Do not reply to this email!</i></b> It was autogenerated by a script, and the sender does not know who you are getting a present for.";
      mailOptions = {
        from: "The Christmas Thing <" + emailUsername + ">",
        to: person.santa.email,
        subject: 'The Christmas Thing!',
        html: body
      };
      console.log("Sending mail to " + person.santa.email);
      results.push(transporter.sendMail(mailOptions, function(error, info) {
        if (error) {
          return console.log(error);
        }
        return console.log('Message sent: ' + info.response);
      }));
    }
    return results;
  };

  module.exports = {
    main: main
  };

}).call(this);
